services:
  neo4j-enterprise:
#    profiles: [ "enterprise" ]
    image: neo4j:4.4-enterprise
    platform: linux/x86_64
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - enterprise-data:/data
      - ./logs/enterprise:/logs
      - ./dumps:/dumps
      - ./scripts:/scripts

  neo4j-community:
#    profiles: [ "community" ]
    image: neo4j:4.4-community
    platform: linux/x86_64
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - community-data:/data
      - ./logs/community:/logs
      - ./dumps:/dumps
      - ./scripts:/scripts


volumes:
    enterprise-data:
    community-data:
